# 1. באיזו מערכת הפעלה להשתמש? (Node.js גרסה 20 על לינוקס קל)
FROM node:20-alpine

# 2. איפה הקוד ישב בתוך ה"מחשב הווירטואלי"?
WORKDIR /usr/src/app

# 3. העתקת קבצי ההגדרות והתקנת הספריות
COPY package*.json ./
RUN npm install

# 4. העתקת כל שאר הקוד שלנו
COPY . .

# 5. בניית הקוד (TypeScript -> JavaScript)
RUN npm run build

# 6. חשיפת הפורט של השירות (3005)
EXPOSE 3005

# 7. הפקודה שתריץ את השירות כשהקונטיינר עולה
CMD ["npm", "start"]