name: Production CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'order-system/services/**' # ירוץ רק כשמשהו בתיקיית השירותים משתנה

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            order-service: 'order-system/services/order-service/**'
            inventory-service: 'order-system/services/inventory-service/**'
            intelligence-service: 'order-system/services/intelligence-service/**'
            notification-service: 'order-system/services/notification-service/**'
            payment-service: 'order-system/services/payment-service/**'

  build-and-deploy:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.services != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJSON(needs.detect-changes.outputs.services) }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          SERVICE_NAME: ${{ matrix.service }}
        run: |
          docker build -t $ECR_REGISTRY/$SERVICE_NAME:${{ github.sha }} ./services/$SERVICE_NAME
          docker push $ECR_REGISTRY/$SERVICE_NAME:${{ github.sha }}
          docker tag $ECR_REGISTRY/$SERVICE_NAME:${{ github.sha }} $ECR_REGISTRY/$SERVICE_NAME:latest
          docker push $ECR_REGISTRY/$SERVICE_NAME:latest

      - name: Update ECS Service
        run: |
          aws ecs update-service --cluster yaniv-main-cluster --service ${{ matrix.service }} --force-new-deployment